### PR TITLE
(multiple) Update to use the Chocolatey AU module

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description

The Chocolatey Community Edition of AU is meant to be renamed to
Chocolatey AU. THe changes in this commit makes the changes that are
necessary to be compatiblte with this module rename.

## Motivation and Context

To have a working update system as quick as possible.

## How Has this Been Tested?

Manually tested by pulling in the changes from chocolatey-au develop branch, as attempt to check for updates on all packages.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)
- [x] Other

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [ ] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
It is expected that this PR will fail even when Chocolatey AU has been released, as it touches all packages in the repository, which some does not work at the moment.

**Review by corbob — APPROVED** [review]
LGTM!

**Comment by corbob** [comment]
The Chocolatey AU release is in progress. Marking this as ready for review.

**Comment by corbob** [comment]
Thanks for getting this updated @AdmiringWorm (Sorry to the code owners for any pings this might have sent out 😬 )

**Pull request merged**
