### PR TITLE
(freecad) Clarify where to raise issues / questions

### PR DESCRIPTION
**Pull request by pauby**
## Description
I've updated the README.md file for several packages. These should flow into the `description` in the .nupspec file. I also moved the `Notes` section of the `description` to the bottom to make it more prominent (first thing people see when they scroll up / last when they scroll down).

## Motivation and Context

Questions are still being asked via Disqus for many packages. As Disqus is generally not responded to, it makes sense to clarify where questions and issues should be raised. Going forward, we should add this to all packages.

## How Has this Been Tested?
I haven't tested it as its markdown.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Review by AdmiringWorm — CHANGES_REQUESTED** [review]
I think you possibly edited the wrong file here.

These changes should have been in the Readme.md file, instead of the nuspec.

**Comment by pauby** [comment]
Absolutely right @AdmiringWorm - apologies. No idea what happened there.

**Comment by AdmiringWorm** [comment]
> Absolutely right @AdmiringWorm - apologies. No idea what happened there.

It happens to the best of us.

As I mentioned on Slack, I am fine with these description changes being committed directly into the repository so if you want to update the `freecad` description directly into the repository along with description changes for other packages, we could close this PR instead of updating it.

That is up to you though.

**Comment by pauby** [comment]
Lets close this and I'll update it directly.

**Pull request closed without merging**
