### PR TITLE
Change the api-url to use the stable version

### PR DESCRIPTION
**Pull request by ralfbosz**
The api-url used for Google Chrome is not the Google Chrome version that will be downloaded.

## Description
The url is pointing to the extended releases. These are well behind and also not the version that will be downloaded from the url at this time (giving mismatch on hash). Move it to the stable-url which do match the downloaded msi.

## Motivation and Context
- The versions of extend are way behind
- Hash mismatch when doing fresh install
- 
## How Has this Been Tested?
- Created the package with choco pack and the right hashes.
- 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [ ] Issue 1 link
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-packages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by pauby** [comment]
This was changed only a [couple of weeks ago](https://github.com/chocolatey-community/chocolatey-packages/commit/5513e36fa726b985d3d5a380cf8ebece1c9a10cf) by @rdenny-vdc - can you comment on this?

We can't keep updating this URL, so we need some clarity on what is the right thing to use (I have no horse in this race as I don't use Google Chrome).

**Comment by rdenny-vdc** [comment]
> This was changed only a [couple of weeks ago](https://github.com/chocolatey-community/chocolatey-packages/commit/5513e36fa726b985d3d5a380cf8ebece1c9a10cf) by @rdenny-vdc - can you comment on this?
> 
> We can't keep updating this URL, so we need some clarity on what is the right thing to use (I have no horse in this race as I don't use Google Chrome).

I 100% agree on this change, and it was something that was spoken about in the Chocolatey package comments [here](http://disq.us/p/2xfb82q) and I suggested this exact change. I support this change

**Comment by ralfbosz** [comment]
The current url does not match the downloaded msi, no idea where you can download the extended version, but the stable url matches the msi-download. With the current url the version is several version behind.

**Comment by pauby** [comment]
> I 100% agree on this change, and it was something that was spoken about in the Chocolatey package comments [here](http://disq.us/p/2xfb82q) and I suggested this exact change. I support this change. Only thing I wasnt sure of was what would happen to package version numbering.

I'm confused as why you made the change to the extended release if you support it being on stable?

This doesn't affect this PR, but I am concerned about the time it took to put the PR up, review the change, and now we're making another change. Trying to understand the why.

**Comment by rdenny-vdc** [comment]
> > I 100% agree on this change, and it was something that was spoken about in the Chocolatey package comments [here](http://disq.us/p/2xfb82q) and I suggested this exact change. I support this change. Only thing I wasnt sure of was what would happen to package version numbering.
> 
> I'm confused as why you made the change to the extended release if you support it being on stable?
> 
> This doesn't affect this PR, but I am concerned about the time it took to put the PR up, review the change, and now we're making another change. Trying to understand the why.

I worked on the package to try and get it working again, I didnt know at the time there were two different versions at the time and trusted the information I was given. The full PR conversation is here. 

https://github.com/chocolatey-community/chocolatey-packages/pull/2396#pullrequestreview-1820130345

This was my first contribution.

**Review by pauby — APPROVED** [review]

**Comment by pauby** [comment]
Having spoken to the team, everybody thinks this sounds like a reasonable change.

Thanks @ralfbosz for your contribution!

**Comment by mems** [comment]
#2399 is the same fix as this one, but for `googlechromebeta`

**Pull request merged**
