### PR TITLE
(tor-browser) Force package update

### LINKED ISSUE #2146: (tor-browser) v12.0.3 checksums are incorrect
### Chocolatey Version

1.3.0

### Chocolatey License

None

### Package Version

12.0.3

### Current Behaviour

v12.0.3 is checking against incorrect (possibly outdated) checksums.

32-bit: 8cf1dafe65efe4a9a732191ab5fa962ae75513694cc802b462abf0ae40f64a3a
64-bit: 94c66cde8a8f6744971553deba450b3e2bf2ad17f0d3129853591a050801a58c

### Expected Behaviour

Package should check against current checksums.

32-bit: A880112BF2927FE02DFCB7550FB1780DFEC8AA5E332D2CD9897C503A018EE02F
64-bit: 8F9E526DA7D1ADAA5C6C7BE88412E9E6C7EAB9AF1B5F080B0D674F5B35F5C4BF

### Steps To Reproduce

`choco install tor-browser --version=12.0.3`

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.22621.0
- PowerShell Version: 5.1.22621.963
- Shell: PowerShell
```

### Chocolatey Log

```shell
https://gist.github.com/brogers5/c1f225d02e2837486cc8e008c7bc71d9
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by brogers5**
## Description
This changeset adds a message-only commit which should prompt AU to forcibly update the `tor-browser` package.

## Motivation and Context
Fixes #2146.

The latest version (v12.0.3)'s checksums are incorrect (possibly outdated) and need to be updated. A package fix version needs to be published with corrected checksums.

This should trigger AU to make the required changes and push an updated package to the Community Repository.

## How Has this Been Tested?
Executed `.\update_all.ps1 -Name tor-browser -ForcedPackages tor-browser` to forcibly build an updated package locally.

Inspected the resulting changes to `chocolateyInstall.ps1` and confirmed checksums have been updated (which still matches what I originally documented).

Installed the test package using `choco install tor-browser --source="'.;https://community.chocolatey.org/api/v2/'"` (to prioritize local packages while sourcing dependencies from the Community Repository).

Confirmed the resulting package installs the 64-bit variant successfully, without requiring checksums to be ignored or overridden.

Uninstalled the test package using `choco uninstall tor-browser`.

Reinstalled the test package to test the 32-bit checksum using `choco install tor-browser --source="'.'" --forcex86`.

Confirmed the resulting package installs the 32-bit variant successfully, without requiring checksums to be ignored or overridden.

## Screenshot (if appropriate, usually isn't needed):
N/A

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
@brogers5 Apologies. I didn't realise all this needed was a fix version of the package.

If we merge the PR, then it won't be picked up as the merge commit would eed to be updated too. So I just pushed https://github.com/chocolatey-community/chocolatey-packages/commit/a85470673cda09812d13a8de5db954447ef7bdc7 to fix this. [Version 12.0.3.20230224 has just been pushed to CCR](https://community.chocolatey.org/packages/tor-browser/12.0.3.20230224) and should be available in a few hours.

**Comment by brogers5** [comment]
For future reference, is a squash or rebase merge not an option for this repository?

**Comment by pauby** [comment]
I'll leave @AdmiringWorm to answer that.

**Comment by AdmiringWorm** [comment]
> For future reference, is a squash or rebase merge not an option for this repository?

No, neither squash nor rebase merges are enabled for this repository.
Doing this through the GitHub UI doesn't squash or rebase things in the desired format. If a rebase is needed, it needs to be done manually. Squashing commits may cause information about the commits to be lost, so we only do this if necessary.

**Pull request closed without merging**
