### PR TITLE
Fix Speccy checksum

### PR DESCRIPTION
**Pull request by asheroto**
## Description
Checksum changed in Speccy, install is currently failing due to checksum error. Package version appears to be the same. Had to adjust version number for package verifier to succeed.

## Motivation and Context
see above

## How Has this Been Tested?
Packed and confirmed install

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
@asheroto can you remove the 'Original Location' section in the description above? Its not needed.

**Comment by asheroto** [comment]
Done thanks!

**Comment by asheroto** [comment]
Do I need to do anything else on this?

**Comment by pauby** [comment]
Not until somebody reviews it.

**Comment by AdmiringWorm** [comment]
This should have been reviewed and mentioned long before now, and I apologize for the delay.

@asheroto I am failing to see exactly what this PR provides.
Speccy is an automatic package, so manually updating the URL or the checksum would not be correct, as these are updated automatically when the package is pushed to the Chocolatey Community Repository.

If the checksum is wrong, then what is needed is for one of the maintainers of the repository to queue up a new fix version to be released. But before that is done, the checksum being wrong, is that just the case in this repository or is it also the case for when attempting to install the package from Chocolatey Community Repository?

**Comment by asheroto** [comment]
Hey @AdmiringWorm, thanks for your response. I will close this PR as I failed to realize it was set up as an automatic package.

**Comment by racinmat** [comment]
Hi, what is the status? The checksum is still incorrect and I can not install speccy using chocolatey. Where should it be updated correctly?

**Comment by pauby** [comment]
@racinmat this issue is closed. Please raise a new issue.

**Pull request closed without merging**
