### PR TITLE
(cyg-get) Space in $cygRoot

### PR DESCRIPTION
**Pull request by jccolson**
Correct a bug when $cygRoot contain space.

## Description

Adding some " to allow space in variable $cygRoot.

## Motivation and Context

If CygWin is installed in "C:\Program Files\CygWin64", "cyg-get firefox" install defaults packages and firefox in the directory "C:\Program".

https://github.com/chocolatey-community/chocolatey-packages/issues/2489

## How Has this Been Tested?

choco install -y --params "/InstallDir:'C:\Program Files\CygWin64' /site:'ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/sources.redhat.com/cygwin/'" Cygwin
choco install -y cyg-get
cyg-get install firefox

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
Please go back to the description and amend it to provide the correct information and ensure you read the required guidelines and make the necessary changes.

**Comment by jccolson** [comment]
@pauby  I don't know how to complete "Open issues" in "Original Location".
I have put the link to the issue in "Motivation and Context".

**Comment by pauby** [comment]
The last bit needs to be removed. As the comments on the template indicate, its only for migrations.

Not that I haven't looked at this package for this PR, but it may be necessary for a new package to be released manually.

**Comment by jccolson** [comment]
@pauby Can I help you to create the new version ?

**Comment by pauby** [comment]
@jccolson I'm not sure what you are asking. I am not creating a new version.

**Comment by jccolson** [comment]
@pauby  You say : "it may be necessary for a new package to be released manually". It's not a new version of cyg-get package ?

**Comment by pauby** [comment]
> "it may be necessary for a new package to be released manually". It's not a new version of cyg-get package ?

I understand now. Thanks for clarifying. 

_I_ am unlikely to be releasing the new package. Whoever picks up this PR to review will likely do that.

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@jccolson your changes have been merged. Thanks for your contribution 👍

I apologize for the delay in getting this PR merged.

**Pull request merged**
