### PR TITLE
(blender) Uninstall fails when multiple software versions installed

### LINKED ISSUE #1795: (blender) Duplicate registry keys matched on uninstall
**choco uninstall blender**
```
Chocolatey v0.12.1
Uninstalling the following packages:
blender

blender v3.0.1
WARNING: 2 matches found!
WARNING: To prevent accidental data loss, no programs will be uninstalled.
WARNING: Please alert the package maintainer that the following keys were matched:
WARNING: - blender
WARNING: - blender
```

### PR DESCRIPTION
**Pull request by pauby**
## Description
Updated the description notes to warn that when multiple versions of Blender are installed, the package will fail to uninstall.

Fixes #1795 

## Motivation and Context
The installer allows multiple versions to be installed and Chocolatey doesn't know which one to uninstall, so it fails. In the [comment](https://github.com/chocolatey-community/chocolatey-packages/issues/1795#issuecomment-1040041182) it was agreed that it wasn't desirable for all versions to be uninstalled.

## How Has this Been Tested?
It hasn't. This is an update to the description field.

## Screenshot (if appropriate, usually isn't needed):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
This is failing for an unrelated issue.

**Review by AdmiringWorm — CHANGES_REQUESTED** [review]

**Comment by pauby** [comment]
This is ready for review again @AdmiringWorm

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@pauby your changes have been merged, thanks for your contribution 👍

**Pull request merged**
