### PR TITLE
(python3-streams) Fix copyright reading logic and zip URL generation in python3-streams

### PR DESCRIPTION
**Pull request by robmoss2k**
## Description

As per [CPython issue #2672](https://github.com/python/pythondotorg/issues/2672), alpha and beta builds have no official docs built. Furthermore, as of [CPython PR #124489](https://github.com/python/cpython/pull/124489), the archives we previously referenced are no longer built. The change applies from Python 3.12 onwards based on what I can see in the docs archive.

## Motivation and Context

The more recent versions of Python do not get packages built, as per [Issue #2555](https://github.com/chocolatey-community/chocolatey-packages/issues/2555). The [previous PR](https://github.com/chocolatey-community/chocolatey-packages/pull/2575) did not work for the 3.14 alpha releases and, based on the CPython issue, may continue to break for new releases.

## How Has this Been Tested?

I tested the Python3 update script directly and saw the correct versions referenced. I then tested via test_all.ps1 and again saw the correct versions referenced. I then used the generated package files and ran a local test install. I'm running PowerShell 7.4.6 on Windows 11.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [X] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [X] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [X] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [X] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by yan12125** [comment]
With this approach 3.14 works but 3.12 fails. Could you have a look?
```
Downloading to python-3.12.8.exe - https://www.python.org/ftp/python/3.12.8/python-3.12.8.exe
Downloading to python-3.12.8-amd64.exe - https://www.python.org/ftp/python/3.12.8/python-3.12.8-amd64.exe
MethodInvocationException: C:\Users\yen\Downloads\chocolatey-packages\automatic\python3-streams\update.ps1:42
Line |
  42 |    $response_stream = $webrequest.GetResponse().GetResponseStream()
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."

```

**Comment by robmoss2k** [comment]
@yan12125 Thanks for picking that up - that's fixed now, and I also removed a logging statement I shouldn't have committed. I believe this is good to go now, and I've learned some useful things along the way 😄

**Review by TheCakeIsNaOH — APPROVED** [review]
Looks good to me.

**Comment by TheCakeIsNaOH** [comment]
Thanks for getting it working on v3.14.x
Still need a review from one of the people on the chocolatey-team-maintainers,

**Review by Windos — APPROVED** [review]
Looks good!

**Pull request merged**
