### PR TITLE
(freecad) Update name to make the package active

### PR DESCRIPTION
**Pull request by RedBaron2**
@AdmiringWorm 

## Description

I forgot to update the file name to make the package active again ☹️ 
This will help that and is updated to take care of files not being removed before packing.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] Issue 1 #1966 
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-packages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by adrianinsaval** [comment]
Anything holding this back?

**Comment by RedBaron2** [comment]
@adrianinsaval 
Just the chocolatey team in doing a review. They don't seem to have the personnel to review this PR currently.
I suggest that the FreeCAD group check into taking over this package. Should this PR take any longer to be reviewed and merged.

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@RedBaron2 thanks for getting this updated!

**Pull request merged**
