### PR TITLE
(1password) Add support for 1password v8.x (fixes #1773)

### LINKED ISSUE #1773: (1password) Update to Version 8.x
Can the 1passoword package be updated to version 8.x (I've had a look and there seems to be ongoing issue under discussion/fix regarding 1password, but that's for V7.x

Wondering if upgrading to V8 will change the way things work and will then also solve the issues with V7.x :)

### PR DESCRIPTION
**Pull request by egerlach**
## Description
* 1password v8 doesn't have the same URL redirect available to it. Instead, parse the HTML page from the update server to find the links to the downloads.
* Also convert v4 and v7 to this method of getting new versions.
* 1password v7 is maintained in a separate stream, confusingly named OPW6 because major version 7 is kept in the same update stream as v6 on the AgileBits update server.
* Beta streams for all three major versions are included. In beta streams for v4 and v8, the fourth version component is used for the build number, which is included in the upstream version.
* 1password.json has been carefully updated so that the most recent item in the stream that is also available in the community repo is represented. This ensures that correct new versions are built and existing versions are skipped and correctly recorded in this file.
* Nightly versions are silently discarded

## Motivation and Context

Fixes #1773 

## How Has this Been Tested?
* Ran `update.ps1` to generate new packages
* Installed each of the packages in [`chocolatey-test-environment`](https://github.com/chocolatey-community/chocolatey-test-environment) (which was an adventure in and of itself)
* Tested resulting packages on a Windows 10 VM and a Windows 10 desktop (mine)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by egerlach** [comment]
Updated comments on testing. While I was able to test all of the 1password 4.x and 1password 7.x packages on `chocolatey-test-environment`, I could not do so with 1password 8.x because Windows Server 2012 is no longer supported. Instead I tested the packages on a Windows 10 VM and a Windows 10 desktop.

**Comment by pauby** [comment]
The new Chocolatey Test Environment is based on [Windows Server 2019](https://blog.chocolatey.org/2023/01/updating-package-services-image-win2019).

**Comment by egerlach** [comment]
> The new Chocolatey Test Environment is based on [Windows Server 2019](https://blog.chocolatey.org/2023/01/updating-package-services-image-win2019).

Ah, I missed that. Will adapt that to my environment and then I'll re-test.

**Comment by AdmiringWorm** [comment]
@egerlach I recommend holding off on making any changes to this pull request for now.

We have had some internal discussions about whether we should keep maintaining this package in this repository, create an RFM request to give it away to new maintainers or ask the developers of 1password if they are interested in taking over the maintenance.

I'll move this PR into a draft for now, but it may be closed once a decision and a result have been achieved.

**Comment by JPRuskin** [comment]
I've reached out to 1Password about this.

**Comment by egerlach** [comment]
Thanks @AdmiringWorm and @JPRuskin for the clarity of your status. It's refreshing not to be in limbo on a PR :)

I've posted my thoughts in [the discussion](https://github.com/chocolatey-community/chocolatey-packages/discussions/1982#discussioncomment-4863720) as they're off-topic for the PR.

**Comment by pauby** [comment]
@AdmiringWorm @JPRuskin @egerlach I'm keen to move this PR forward but we should also consider closing it if there is no movement.

@JPRuskin any update from 1Password?

**Comment by imiddleton1** [comment]
Has anyone tried using this link?  It's always the latest version.  It was sent to me by 1password support:

https://downloads.1password.com/win/1PasswordSetup-latest.msi

**Comment by pauby** [comment]
As there has been no movement on this, I'm going to close it. We can always reopen it again later.

**Pull request closed without merging**
