### PR TITLE
(freecad) Rewrite to address issue 1922

### PR DESCRIPTION
**Pull request by RedBaron2**
@gep13 @AdmiringWorm @TheCakeIsNaOH 
## Description

This will address the issue #1922 and make the script future proof. It is meant to make the package up and working for the community.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] Issue 1 #1922 
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-packages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@RedBaron2 your changes have been merged, thanks for your contribution 👍

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Could you check as to the error in the latest build on Appveyor
`Chocolatey v1.1.0 Attempting to push freecad.0.20.0.29365-dev.nupkg to https://push.chocolatey.org Failed to process request. 'Request Entity Too Large'.  The remote server returned an error: (413) Request Entity Too Large.. Chocolatey v1.1.0 Attempting to push freecad.0.20.0.1.nupkg to https://push.chocolatey.org Failed to process request. 'Request Entity Too Large'.  The remote server returned an error: (413) Request Entity Too Large.. Chocolatey v1.1.0 Attempting to push freecad.portable.0.20.0.1.nupkg to https://push.chocolatey.org Failed to process request. 'Request Entity Too Large'.  The remote server returned an error: (413) Request Entity Too Large..`
--
Thanks

**Comment by AdmiringWorm** [comment]
> @AdmiringWorm Could you check as to the error in the latest build on [Appveyor](https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f#freecad)
> 
> -- Thanks

Looking at the error message, it specifically say `Request Entity Too Large`. This typically means that the package has gotten above 200MB and can no longer be pushed to community.chocolatey.org.

I haven't verified whether that is the case or not though.

**Pull request merged**
