### PR TITLE
(k9s) download zip instead of tar.gz

### PR DESCRIPTION
**Pull request by danielkoek**
## Description

New releases are now in zip format instead of tar.gz, this is to update that
## Motivation and Context

Releases can now be pulled properly
## How Has this Been Tested?

It is only a zip, so not necessary to locally test it.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [ ] Issue 1 link
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-packages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by pauby** [comment]
@danielkoek can you please go back and complete the PR template? We need that information before we can review this.

**Comment by danielkoek** [comment]
@pauby  done that to the best of my ability!

**Comment by AdmiringWorm** [comment]
@moebius87, as the code owner of this package, can you please review the changes for this package so it can be merged?

**Comment by pauby** [comment]
@moebius87 in following up on this from @AdmiringWorm tagging you last week. If you no longer wish to be the code owner of this package, please let us know.

**Review by pauby — APPROVED** [review]

**Comment by pauby** [comment]
This looks good to me. I'll push a commit removing @moebius87 from the CODEOWNERS.

**Comment by pauby** [comment]
@danielkoek awesome work! Thanks for your contribution!

**Comment by danielkoek** [comment]
@pauby thanks for getting it all merged in!!

**Pull request merged**
