### PR TITLE
Fix package name replacements in python3-streams

### PR DESCRIPTION
**Pull request by Jackenmen**
## Description
Fixed the issues with package name replacements in python3-streams package that I mentioned in #1993.

## Motivation and Context
The package is failing automated package testing on Chocolatey Community Repository.

## How Has this Been Tested?
Checked the artifacts generated by AppVeyor

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by Jackenmen** [comment]
@AdmiringWorm you'll probably be interested in this.

**Review by JPRuskin — APPROVED** [review]
LGTM! Thanks for getting this sorted.

**Comment by Jackenmen** [comment]
Alright, *this time* `python311` passed Chocolatey Community Repository's automated testing, progress! :)

Now it only needs to wait to get approved by a moderator.

**Comment by AdmiringWorm** [comment]
Indeed, once that package is approved, I will resume the updating of the `python3` package so it can take a dependency on any package versions pushed.

**Pull request merged**
