### PR TITLE
(graphviz) Update changelog URL in graphviz.nuspec

### PR DESCRIPTION
**Pull request by ferdnyc**
## Description
Update URL to upstream changelog file. The graphviz repo's default branch has been renamed from `master` to `main `.

## Motivation and Context
Prevents 404 when following link under "Release Notes" on Chocolatey website.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
LGTM, and the failures are not related to this PR.

**Comment by AdmiringWorm** [comment]
@ferdnyc your changes have been merged. Thanks for your contribution 👍

**Comment by ferdnyc** [comment]
Actually, the correct link for release package downloads is https://graphviz.org/download/#windows, where 10.0.1 packages are at the bottom of the list (for some reason).

**Comment by AdmiringWorm** [comment]
Sounds like the Graphviz updater needs to be updated, can you create a new issue for outdated packages here: https://github.com/chocolatey-community/chocolatey-packages/issues/new/choose (Assuming an issue doesn't already exist).

**Comment by ferdnyc** [comment]
Done as https://github.com/chocolatey-community/chocolatey-packages/issues/2432

**Pull request merged**
