### PR TITLE
(bluegriffon) stopped by it's developper

### PR DESCRIPTION
**Pull request by tunisiano187**
More informations here : http://bluegriffon.org/

## Description
Move bluegriffon to deprecated

## Motivation and Context
The devlopper has definitely stopped this product

## How Has this Been Tested?
not tested

## Screenshot (if appropriate, usually isn't needed):
image

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [X] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [X] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by JPRuskin** [comment]
This makes sense to me, but I notice that none of the other deprecated packages have their update script. Given the error in the build, should we remove that from this and just delete it? It'll still be in the repository history, if needed.

**Comment by tunisiano187** [comment]
I don't know what is the best practices, but indeed it will still be available in the history

**Comment by JPRuskin** [comment]
Are you happy for me to push that change to your branch?

**Comment by tunisiano187** [comment]
Yes of course ;-)

**Review by JPRuskin — APPROVED** [review]
LGTM! Thank you for getting this sorted!

**Pull request merged**
