### PR TITLE
(startallback) Add StartAllBack package

### PR DESCRIPTION
**Pull request by kalsowerus**
## Description

Adds an automatic package for StartAllBack.

## Motivation and Context

https://www.startallback.com/ StartAllBack is the Windows 11 Version of StartIsBack.

## How Has this Been Tested?

Tested using the [chocolatey-test-environment](https://github.com/chocolatey-community/chocolatey-test-environment).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by kalsowerus** [comment]
AppVeyor fails with "The procedure entry point IsWow64Process2 could not be located..." (https://ci.appveyor.com/api/buildjobs/djowbe2coxj434kd/artifacts/installError_startallback.jpg). StartAllBack seems to require Windows 10 1709 / Windows Server 2016 1709 (https://learn.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2). What version of Windows does AppVeyor use?

**Comment by pauby** [comment]
> StartAllBack seems to require Windows 10 1709 / Windows Server 2016 1709

Can you add that check into the package?

**Comment by kalsowerus** [comment]
@pauby I'm not much of an expert on this. Would a simple `[System.Environment]::OSVersion.Version.Build -ge 16299` check cover all cases?

**Comment by pauby** [comment]
@kalsowerus If you're asking me can you use that code, then the answer is yes. If you're asking me if that code works and ensures that the package only installs on those OS's you mentioned, I don't know.

**Comment by TheCakeIsNaOH** [comment]
> What version of Windows does AppVeyor use?

Based on the config, it looks like server 2016, which is based on windows 1607, which would not work
https://github.com/chocolatey-community/chocolatey-packages/blob/master/.appveyor.yml#L7
https://www.appveyor.com/docs/windows-images-software/

> I'm not much of an expert on this. Would a simple `[System.Environment]::OSVersion.Version.Build -lt 16299` check cover all cases?

I believe it would for all currently released Windows version, but if in the future Microsoft released a new major version while resetting/decrementing the build version, then this would break. The major and minor versions should also be checked:
https://github.com/chocolatey-community/chocolatey-packages/blob/da3efbc83ddf7fb6f1ba1a0671cfe0a9c0dbe4ca/automatic/smartftp/tools/chocolateyInstall.ps1#L3-L8

**Comment by kalsowerus** [comment]
@TheCakeIsNaOH Thanks for the snippet, I updated the install script.

**Comment by pauby** [comment]
@kalsowerus I'm just looking over this PR and realised it's a new package? Did you raise a discussion or otherwise get agreement that the package would be accepted? I can't seem to find anything, and there is nothing linked in the description.

**Pull request closed without merging**
