### PR TITLE
(keepassxc) remove 32-bit support

### LINKED ISSUE #1829: keepassxc
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.7.0

### Download location

https://github.com/keepassxreboot/keepassxc/releases/download/2.7.0/KeePassXC-2.7.0-Win64.msi

### Package Page

https://community.chocolatey.org/packages/keepassxc

### PR DESCRIPTION
**Pull request by geicht**
## Description

Removes all code used for the 32-bit installer of KeePassXC as it isn't supported anymore.

## Motivation and Context

Fixes #1829 

## How Has this Been Tested?

I updated the package with the update.ps1 script and successfully installed/uninstalled it afterwards.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [ ] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by slycordinator** [comment]
This would retroactively remove 32-bit support from the package for version 2.6.6, in spite of the fact that 2.6.6 supports 32-bit.

Starting with version 2.7, 32-bit support was dropped from upstream.

**Comment by yan12125** [comment]
> This would retroactively remove 32-bit support from the package for version 2.6.6, in spite of the fact that 2.6.6 supports 32-bit.

I guess existing `*.nupkg` files for 2.6 will not be affected by updated nuspec?

**Comment by geicht** [comment]
@slycordinator i believe the confusion stems from there not actually being a version update of the package within the PR.
KeePassXC not releasing a 32-bit binary broke the update script for the package, which is what this PR fixes.

With keepassxc being an automated package within this repository and the update script working after the PR is merged, the package will be automatically updated to 2.7.0 and pushed to chocolatey, when the next scheduled AppVeyor build is run.

All versions released on chocolatey prior to the 2.7.0 update won't be affected by this.

**Comment by yan12125** [comment]
Thanks for confirmation!

By the way, KeePassXC now requires vcredist140 https://github.com/keepassxreboot/keepassxc/issues/7564. Maybe add it to dependencies?

**Comment by geicht** [comment]
Yeah, it makes sense to add it. I will push an update in a bit.

**Comment by Windos** [comment]
@geicht good stuff, thanks for your contribution!

**Pull request merged**
