### PR TITLE
(tor-browser) Fix shortcut creation for Tor Browser with /InstallDir param

### PR DESCRIPTION
**Pull request by Destroy666x**
See https://github.com/chocolatey-community/chocolatey-packages/issues/2145 (closed automatically ugh).

## Description
Wrong shortcut is created for Tor Browser if you use `/InstallDir` param. Also the code for ACLs were considering wrong dir in that case as well, but not sure what that's for.

Also note the code is quite messy there in general and could surely be optimized, but that'll be job for someone else, if anyone.

## Motivation and Context
Make desktop shortcut work with `/InstallDir` param.

## How Has this Been Tested?
- `choco pack` in the `tor-browser` folder in git repository
- `choco install tor-browser --debug --verbose --source . --params "'/InstallDir:C:\Portable programs\Tor Browser'" -f`
- Installation completed, desktop got linked to correct executable and working dir

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
This doesn't work in testing. The shortcut is being created on the desktop and pointing to `C:\ProgramData\chocolatey\lib\tor-browser\tools\tor-browser\Browser\firefox.exe`

If you update this, please confirm how you tested it and in which environment.

**Comment by Destroy666x** [comment]
What was the command you used?

**Comment by pauby** [comment]
The command used was `choco install tor-browser --debug --verbose --source 'desktop;chocolatey' --params "'/InstallDir:C:\Portable programs\Tor Browser'" -f

**Comment by Destroy666x** [comment]
@pauby I came back to this and I don't see how it could not work, there's nothing else that could use the old variable, still. I merged newer version into the branch and it still works:
image

I used what I mentioned above, It works both with Tor Browser installed and uninstalled. I don't have enough experience with Chocolatey to state why it doesn't work for you, I'd assume some cache if I was to guess. Perhaps someone else from your team could try?

**Comment by pauby** [comment]
> I used what I mentioned above, just in standard cmd shell on Windows 10

Did you create a package from it and then install the package? Otherwise you're not testing this in a way that mimics how it's going to be used. This is how I did it.

**Comment by Destroy666x** [comment]
Yes, that is once again listed above under "How Has this Been Tested?" section above that you require.

**Comment by pauby** [comment]
I wasn't clear. You said:

> I used what I mentioned above, just in standard cmd shell on Windows 10

So the change you _just_ made doesn't sound like it's been tested in the test environment.

**Comment by Destroy666x** [comment]
Not sure I understand how a testing environment mimics how it'll be used as normal users will install/upgrade it on normal non-VM system with bunch of other packages. But yea, I understand the "clean conditions" part and saw the test environment earlier. Honestly, if only it didn't require 10 GB of space, lots of memory since it's a VM and Vagrant that I normally never use, I'd be more encouraged to use that. I'm wondering how many conributions that prevented.

Regardless, I still fail to see how results could be different on that testing environment and regular Chocolatey environment considering the changes that happened.

**Comment by pauby** [comment]
All PR's are required to be tested in the Chocolatey Test Environment, including any changes made.

I've tested your PR in that environment and there was the issue I've mentioned.

If you're are unable or unwilling to test your fix for that issue in the same environment then we cannot merge it.

**Pull request closed without merging**
