### PR TITLE
(python3-streams) Also lockdown sub-folders

### PR DESCRIPTION
**Pull request by yan12125**
## Description

Fixes https://github.com/chocolatey-community/chocolatey-packages/issues/1840

## Motivation and Context

Close the security hole; make permissions consistent

## How Has this Been Tested?

All sub-folders are limited to administrators, so pip installs to user site-packages as expected if it's run as a normal user. I tested Python 3.9 and 3.12.
```
PS> python3.9.exe -m pip install pyreadline3
Defaulting to user installation because normal site-packages is not writeable
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing collected packages: pyreadline3
Successfully installed pyreadline3-3.4.1
PS> python3.12.exe -m pip install pyreadline3
Defaulting to user installation because normal site-packages is not writeable
Collecting pyreadline3
  Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
Installing collected packages: pyreadline3
Successfully installed pyreadline3-3.4.1
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment. - I got several issues during setting up the test environment, and I prefer not investing time into those issues
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by JPRuskin** [comment]
Is there a reason we're applying this to every level, rather than fixing inheritance? ("it's just the way I did it" is a fine answer, I'm just curious)

**Comment by yan12125** [comment]
I didn't try it as I'm not familiar with permission inheritance. I will check it out when I'm back to my Windows machine next week.

**Comment by yan12125** [comment]
Somehow an unwanted ACL rule for `NT AUTHORITY\Authenticated Users` is left with `GetAccessControl`/`SetAccessControl`, as I described in #1840, and the issue is gone with `Get-Acl`/`Set-Acl`.

**Comment by yan12125** [comment]
@JPRuskin Mind to have another look?

**Comment by pauby** [comment]
@AdmiringWorm @Windos @JPRuskin @gep13 @corbob I don't use Python. I don't know enough about this issue to review it. Could one of you pick it up?

**Comment by Windos** [comment]
@yan12125 - just double checking, does this PR include all of your intended changes?

Just asking as you mention in the description about switching to Write-Debug, but that change isn't included any more. I note a force push in the history here that got rid of the Write-Debug change and replaced it with the switch to Get/Set-Acl cmdlets only.

**Comment by yan12125** [comment]
@Windos thanks for the notice. Yes, this pull request includes all intended changes.

The Write-Debug change is not needed for the new Get/Set-Acl approach. I updated pull request description to avoid confusion.

**Comment by Windos** [comment]
In my testing of this the resulting ACLs on sub directories appear to remain the same as indicated in the issue (authenticated users having write and modify rights.)

Is it possible that
```powershell
Set-Acl -Path $folder -AclObject $acl
```
should be recursive?
```powershell
Get-ChildItem -Path $folder -Recurse -Force | Set-Acl -AclObject $acl
```

**Comment by yan12125** [comment]
Thanks for testing. Coud you share more details about sub directories that still have the issue? I checked permissions with the following command and didn't find a file/directory where `Authenticated Users` can write/modify.
```powershell
Get-ChildItem -Path C:\Python39\ -Recurse -Force | Get-Acl | Format-List > acl.txt
```

JPRuskin and I had a discussion about the non-recursive approach (see comments above), and after that I feel the non-recursive way better in terms of performance of `chocolateyInstall.ps1`.

**Comment by yan12125** [comment]
@Windos Could you have another look? I have been using the new solution with various Python versions for several months, and it's always working fine for me.

**Comment by yan12125** [comment]
Just a trivial rebase, as my branch is more than 1000 commits old.

**Comment by Windos** [comment]
Apologies for the delay @yan12125, just wanted to confirm this is on my list to re-review. I should be getting back to you in a couple of days.

**Comment by Windos** [comment]
I finally had a chance to re-test this today and did so against a handful of operating systems. Pleased to say the change worked across the board.

**Review by Windos — APPROVED** [review]
This change has been effective in all of my testing, thanks for persisting with this, @yan12125

**Pull request merged**
