### PR TITLE
(ghostscript.app) Use AHK for installation after silent install flag removal

### LINKED ISSUE #2221: (ghostscript.app) Package failing verification
## Expected Behavior
The `ghostscript.app` package installs and passes Package Verifier.

## Current Behavior
The latest two packages (at the time of writing this) are failing Package Verifier.

image

The gists indicate the installation is hanging, and #2219 indicates that the installer pop's up. As the package doesn't use Autohotkey for automation, I suspect the silent args have changed for some reason.

## Possible Solution
None.

## Steps to Reproduce (for bugs)
See the gists.

## Context
N/A

## Your Environment
Package Verifier.

### PR DESCRIPTION
**Pull request by maxilampert**
## Description

Add AHK install script after Artifex disabled the silent flag in the GhostScript installer.
Fixes #2221 

## Motivation and Context

Artifex disabled the option to install GhostScript with the silent flag (it's get's always overridden).
Installing Ghostscript with Chocolatey is only possible by using AHK.
Uninstaller does not need adjustments as it still can be run with silent flag.

## How Has this Been Tested?

Tested successfully on latest Windows 11 fully patched.
Edit: Also tested successfully with with the latest chocolatey test environment.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@maxilampert you mentioned in your testing steps that you tested this on your own Windows 11 computer.

We require testing to happen in the [`chocolatey-test-environment`](https://github.com/chocolatey-community/chocolatey-test-environment), is this something you are able to do?

If you are waiting on us to do that testing, that may take several months to happen (all depending on when a repository maintainer has the time available for it).

**Comment by maxilampert** [comment]
@AdmiringWorm Yes, I did test it with the chocolatey-test-environment. The package installation worked fine. Just didn't mention it above as there was a checkbox item for it already.

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@maxilampert your changes have been merged. Thanks for your contribution 👍

**Pull request merged**
