### PR TITLE
(GoogleChromeBeta) Fix - OmahaProxy has been turned down.

### PR DESCRIPTION
**Pull request by tunisiano187**
OmahaProxy has been turned down, so i used the following page to get latest version : https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/beta/versions

## Description
- Replace OmahaProxy by https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/beta/versions
- Take the latest version from that page

## Motivation and Context
Error on Gist of the community and not updated anymore.
https://gist.github.com/choco-bot/a14b1e5bfaf70839b338eb1ab7f8226f/6dd573e1e7c834a559dd42440aba3ef71ace156d#googlechromebeta

## How Has this Been Tested?
Tested on my computer

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [X] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [X] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [X] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [X] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Review by AdmiringWorm — APPROVED** [review]
The changes look good to me.

As this package is missing an original maintainer, are you interested in becoming the original/main maintainer of the package?

This means you will be requested a review from when a change to this package comes in.

If you are interested, please update the `.github/CODEOWNERS` file with your GitHub username, and add the same as the last entry in the `<owners>` section of the nuspec file.

**Comment by TheCakeIsNaOH** [comment]
FYI, this package can't be built in the current appveyor, since the validation extension errors as the package ID contains `beta`, which is why I abandoned #2399

**Comment by tunisiano187** [comment]
I'll add me to the owners, but for the remark it seems OK ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/48913512#L261
I don't understand what you mean.

**Comment by TheCakeIsNaOH** [comment]
Interesting, it was failing for me. I'm not sure what changed.

**Comment by tunisiano187** [comment]
Added myself., 
TheCakeIsNaOH we'll see if there is a problem in the future...

**Comment by AdmiringWorm** [comment]
> FYI, this package can't be built in the current appveyor, since the validation extension errors as the package ID contains `beta`, which is why I abandoned #2399

hmm, that is actually a good point and I think you are correct.
The AppVeyor PR build won't fail, as it is still using an older version of Chocolatey CLI where the validation extension does not load.

Anyways, we'll still get this merged in, but if it starts failing to push a new identifier for the package would be needed.

**Comment by AdmiringWorm** [comment]
@tunisiano187 because you use master has the branch you put in as the PR, I could not update the PR with the reworded commit messages and needed to merge it outside of this. This was merged in https://github.com/chocolatey-community/chocolatey-packages/commit/80348834b7dc4e99f602bef3b5b5b5b091994a8d.

In the future, make sure you do not open a pull request from the master branch, instead use a standalone branch just for the PR.

Still, thank you for your contribution.

**Comment by tunisiano187** [comment]
Hello,
The update looks strange....
on the gist, it shows 
`
nuspec version: 125.0.6422.14-beta
remote version: 125.0.6422.14-beta
`

but the nuspec isn't at 125 but 120...

**Comment by AdmiringWorm** [comment]
Looking at the latest build log, this seems to be just a misreporting in the gist.

I think this happens because `choco pack` failed (probably because of what @TheCakeIsNaOH said previously, this wasn't seen as part of the PR build as PR's builds against the lowest version of Chocolatey CLI we support, which cannot load the community extension).

https://ci.appveyor.com/project/chocolateycommunity/chocolatey-packages/builds/49699826#L2995


Due to the build failure, I'll be moving this package to manual as we can't update the package.
If we want it to work again, the ID needs to change (not sure to what), and we deprecate the beta package.

**Comment by tunisiano187** [comment]
Thank you for the answer.
Can I take it to my own git to automate it?

**Pull request closed without merging**
