### PR TITLE
(docs) Add automatic generation of TOC content

### PR DESCRIPTION
**Pull request by AdmiringWorm**
## Description

This pull request adds a new GitHub Action workflow that will generate and push a new commit to the repository when it needs to update the TOC content for both the Readme.md and Contributing.md files.

## Motivation and Context

To have a TOC available for the files, without the need for us to create the TOC content manually.

## How Has this Been Tested?

1. Tested on my fork to ensure that it works as expected. See https://github.com/AdmiringWorm/chocolatey-coreteampackages/commit/312146ba6f67b7282bf1ebf435fd9e1453611013 as what it will create for this PR.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)
- [x] Documentation

## Checklist:

- [ ] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package). (Will happen automatically)
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

## Original Location

N/A

## Related Issues

Loosely related to #1754

### CODE REVIEW

**Comment by pauby** [comment]
I'm happy to merge this @gep13 ?

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@AdmiringWorm thanks for getting this added!

**Comment by AdmiringWorm** [comment]
nice, looks like it successfully updated the TOC as well: https://github.com/chocolatey-community/chocolatey-packages/commit/d4c4809bce66d00131db53369a5e85bfee091c5b

Wasn't sure who it would commit as though, but looks like @gep13 is the lucky winner 😆

**Comment by gep13** [comment]
> @AdmiringWorm said...
Wasn't sure who it would commit as though, but looks like @gep13 is the lucky winner 😆

I spotted that it was me, but I suspect going forward it will be the person doing the commit/merge into the main branch?

**Comment by AdmiringWorm** [comment]
yeah, that is what I expect to happen at least

**Pull request merged**
