### PR TITLE
(tixati) Fix for app running on update (#2182)

### PR DESCRIPTION
**Pull request by teknowledgist**
## Description
This should fix [issue #2182](https://github.com/chocolatey-community/chocolatey-packages/issues/2182) by ~~first closing~~ *notifying the user and quitting if* any Tixati application processes running on install or uninstall.

## Motivation and Context
The Tixati package is significantly behind because issue #2812 has held it up (and I'm tired of waiting).  The choice was either to fail upgrades (or installs) with a message to close/quit if the Tixati application was running or to unilaterally close the process and perform the upgrade.  I chose the ~~latter~~ *former, after feedback and consideration*.

## How Has this Been Tested?
I started Tixati and then upgraded it via `choco upgrade tixati -y`.  Note:  this PR has not been run through the official Test Environment, but:

1. The current (pre-PR) package code *has* been tested/approved.
2. The added code (`Get-Process` and `Stop-Process`) are compatible back to PowerShell v2 (at least).
3. The problem this fixes can't be tested in an automated way because the application must be running.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the Chocolatey Test Environment(https://github.com/chocolatey-community/chocolatey-test-environment/). _Note that we don't support the use of any other environment_.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
I dint used this application so this may be a stupid question, but what happens if the application is closed without data being saved? Does it save it or is it lost?

**Comment by teknowledgist** [comment]
Ugh!  Asking the good questions.  😉

Based on a quick test, despite a checked option to continue transfers on startup, it does not restart or even list them.  If you re-open a .torrent file, it appears to recognize that it already has some pieces and very quickly checks them and adds to them.  Thus it does not appear to lose information, but I didn't complete the download and test that it works.

That said, it would probably be better to throw the install with a message telling the user to close Tixati first if it happens to be running.  Certainly more safe.

Let's see if I can figure out how to modify my PR...

**Comment by vampiricwulf** [comment]
Dialogue boxes appear during the install process that asks you if you would like it to close Tixati for you. I'm pretty sure it's safe to just tell it to close the program rather than request the user to do so. The old method in the AHK script would be to automatically accept it, but the text on the dialogue boxes changed so it causes the AHK script to fail.

**Review by JPRuskin — APPROVED** [review]
This LGTM, and works as intended.

**Pull request merged**
