### PR TITLE
(codelite) Fix version scraping

### LINKED ISSUE #2176: (codelite) Outdated
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

17.0.0

### Download location

https://downloads.codelite.org/downloads.php?windows_64

### Package Page

https://community.chocolatey.org/packages/codelite

### PR DESCRIPTION
**Pull request by brogers5**
## Description
This changeset adjusts the regex pattern used in scraping the latest stable version info from the [CodeLite download page](https://downloads.codelite.org/), to enable `codelite`'s update script to work correctly.

## Motivation and Context
Fixes #2176.

As of v17.0.0's release, the website no longer contains the word "Release" in the table header that we scrape to determine the latest stable version. This causes `$version` to be set to `$null`, as there are no valid string matches against the current regex pattern.

Resolved by adjusting the regex pattern to reflect this change.

#### Dev

* OS Build: Windows 11 Pro v10.0.22621.0 (64-bit)
* PowerShell version: 7.3.3
* Chocolatey version: 1.3.1

#### Chocolatey Test Environment
* Vagrant Box Version: 3.0.0
* VM Provider: Virtualbox (although practically Hyper-V, since I manually converted the resulting virtual disk)
* OS Build: Windows Server 2019 Datacenter v10.0.17763.0 (64-bit)
* PowerShell version: 5.1.17763.3770
* Chocolatey version: 1.3.1

### Steps

1. Executed `.\update.ps1` locally to confirm that the modified regex pattern behaves as expected, and that the update script completes without errors.
2. Within my local Chocolatey Testing Environment instance, installed the resulting `codelite` v17.0.0 test package with dependencies sourced from the Community Repository (i.e. `choco install codelite --source="'.;https://community.chocolatey.org/api/v2'"`), and confirmed the package installation completes without errors.
3. Uninstalled `codelite` (i.e. `choco uninstall codelite`), answered the uninstaller's dialog prompt, and confirmed the package uninstallation completes without errors.

## Screenshot (if appropriate, usually isn't needed):
N/A

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by brogers5** [comment]
Verification is failing because the uninstall command is timing out. This package's uninstaller has a task dialog that is not suppressed, despite the auto-uninstaller service passing Inno Setup's `/SUPPRESSMSGBOXES` parameter, and requires manual user input for an upgrade/uninstall:

Codelite Uninstall Prompt

Note this behavior is not unique to the new version.

**Comment by pauby** [comment]
@brogers5 I'll take a look at this PR as soon as I can.

Can I ask a favour? Could you raise an issue to have the uninstall automated, likely with AutoHotkey?

**Comment by brogers5** [comment]
@pauby #2181 has been opened for this.

**Comment by AdmiringWorm** [comment]
@brogers5 your changes have been merged, thanks for your contribution 👍

**Pull request merged**
