### PR TITLE
(multiple) Correct `cp1252` encoding in `utf-8`

### PR DESCRIPTION
**Pull request by Benjamin-Loison**
## Description, Motivation and Context

I noticed [an encoding issue in `tools\chocolateyInstall.ps1`](https://github.com/chocolatey-community/chocolatey-packages/blob/e1e5f11fee93dcdf29f7d7486aea70077bdecc40/automatic/tor-browser/tools/chocolateyInstall.ps1#L21) of [`tor-browser`](https://community.chocolatey.org/packages/tor-browser), so I found and solved other similar issues thanks to the Python script given in the first commit description.

## How Has this Been Tested?
Except:
- https://github.com/chocolatey-community/chocolatey-packages/commit/ee1d11b172235e1a947a46e6dc6de27ba0574cfb#diff-aae96f15f0ec487d0ff4b45ad768a1c36c8378749fe23d9e2f5e690168a285f4L2-R2
- https://github.com/chocolatey-community/chocolatey-packages/commit/5fef977571d5ba5c5c2259392fc4b644ce677f6b

I am sure of my method.

## Checklist:
- [X] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by Benjamin-Loison** [comment]
`pspp` AppVeyor issue isn't related to my two changes: [`Readme.md`](https://github.com/chocolatey-community/chocolatey-packages/pull/2304/files#diff-dae9c82c36b05b130601346b333a46db54e52d50c13d129beee4588855267d30) and [`pspp.nuspec`](https://github.com/chocolatey-community/chocolatey-packages/pull/2304/files#diff-348b3346303313649ac26de1a97ece2e2ef9a0446b2a97e7425b599d862ff1cb).

**Comment by pauby** [comment]
This looks fine to me, and I am going to approve it. But would like a second pair of eyes on it in case I'm missing something obvious.

**Review by pauby — DISMISSED** [review]

**Review by AdmiringWorm — APPROVED** [review]
LGTM, this was most likely had happened before AU properly supported UTF-8 (no-BOM) encodings. Thank you for getting these fixed up.

**Review by AdmiringWorm — CHANGES_REQUESTED** [review]
Can you please rebase your PR and combine the second commit into the first one?

As you have used your master branch as the head, I can not rebase and push this PR on your behalf.

Thanks.

**Comment by Benjamin-Loison** [comment]
Let me know if what I did isn't fine.

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Pull request merged**
