### PR TITLE
(openshift-cli) Remove invalid mailingListUrl

### LINKED ISSUE #2124: (openshift-cli) Failing Package Validator
### Chocolatey Version

1.2.1

### Chocolatey License

None

### Package Version

4.11.20

### Current Behaviour

Package is failing Package Validator with an invalid `<mailingListUrl>`.

### Expected Behaviour

_No response_

### Steps To Reproduce

This is a Validator fail.

### Environment

```markdown
N/A
```

### Chocolatey Log

```shell
N/A
```

### Anything else?

Versions 4.11.20, 4.11.21, 4.11.22 and 4.12.0 have all failed.

### PR DESCRIPTION
**Pull request by pauby**
## Description
The `mailingListUrl` is now invalid so it was removed.

**Once this is merged, the package will need to be pushed again.**

Fixes #2124 

## Motivation and Context
Package is failing Package Validator with an invalid `mailingListUrl`

## How Has this Been Tested?
It hasn't been tested. The line containing the `mailingListUrl` was removed from the .nuspec file.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] I have updated the package description and it is less than 4000 characters.
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by pauby** [comment]
Version 4.11.21, 4.11.22 and 4.12.0 are 'Waiting on maintainer' so once merged the latest will need to be pushed again.

**Review by JPRuskin — APPROVED** [review]
This seems good. That is an invalid link.

**Review by corbob — APPROVED** [review]
This Looks Good To Me

**Comment by AdmiringWorm** [comment]
As this has been approved by both @JPRuskin and @corbob I'll get this merged and push up a fixed version of `4.12.0`

**Pull request merged**
